name: Buildifier
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: buildifier
        run: bazel run --enable_bzlmod //.github/workflows:buildifier.check
