name: Release
"on":
  push:
    tags:
      - v*.*.*
permissions:
  contents: write
jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v6
    with:
      release_files: rules_abcue-*.tar.gz
